/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuizSetupRouteImport } from './routes/quiz-setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminComingSoonRouteImport } from './routes/admin.coming-soon'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminMcqUploadRouteImport } from './routes/admin.mcq-upload'
import { Route as AdminPaymentProofsRouteImport } from './routes/admin.payment-proofs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAnalyticsRouteImport } from './routes/student.analytics'
import { Route as StudentAnnouncementsRouteImport } from './routes/student.announcements'
import { Route as StudentBookmarksRouteImport } from './routes/student.bookmarks'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentPracticeRouteImport } from './routes/student.practice'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentQuizReviewRouteImport } from './routes/student.quiz-review'
import { Route as StudentQuizSessionRouteImport } from './routes/student.quiz-session'
import { Route as StudentSubscriptionRouteImport } from './routes/student.subscription'
import { Route as StudentBooksIndexRouteImport } from './routes/student.books.index'
import { Route as StudentQuizChapterIdRouteImport } from './routes/student.quiz.$chapterId'
import { Route as AdminBooksBookIdChaptersRouteImport } from './routes/admin.books.$bookId.chapters'
import { Route as StudentBooksBookIdChaptersRouteImport } from './routes/student.books.$bookId.chapters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSetupRoute = QuizSetupRouteImport.update({
  id: '/quiz-setup',
  path: '/quiz-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComingSoonRoute = AdminComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMcqUploadRoute = AdminMcqUploadRouteImport.update({
  id: '/mcq-upload',
  path: '/mcq-upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentProofsRoute = AdminPaymentProofsRouteImport.update({
  id: '/payment-proofs',
  path: '/payment-proofs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAnalyticsRoute = StudentAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAnnouncementsRoute = StudentAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBookmarksRoute = StudentBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizReviewRoute = StudentQuizReviewRouteImport.update({
  id: '/quiz-review',
  path: '/quiz-review',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizSessionRoute = StudentQuizSessionRouteImport.update({
  id: '/quiz-session',
  path: '/quiz-session',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubscriptionRoute = StudentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBooksIndexRoute = StudentBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizChapterIdRoute = StudentQuizChapterIdRouteImport.update({
  id: '/quiz/$chapterId',
  path: '/quiz/$chapterId',
  getParentRoute: () => StudentRoute,
} as any)
const AdminBooksBookIdChaptersRoute =
  AdminBooksBookIdChaptersRouteImport.update({
    id: '/$bookId/chapters',
    path: '/$bookId/chapters',
    getParentRoute: () => AdminBooksRoute,
  } as any)
const StudentBooksBookIdChaptersRoute =
  StudentBooksBookIdChaptersRouteImport.update({
    id: '/books/$bookId/chapters',
    path: '/books/$bookId/chapters',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz-setup': typeof QuizSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/books': typeof AdminBooksRouteWithChildren
  '/admin/coming-soon': typeof AdminComingSoonRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mcq-upload': typeof AdminMcqUploadRoute
  '/admin/payment-proofs': typeof AdminPaymentProofsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/bookmarks': typeof StudentBookmarksRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quiz-review': typeof StudentQuizReviewRoute
  '/student/quiz-session': typeof StudentQuizSessionRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/quiz/$chapterId': typeof StudentQuizChapterIdRoute
  '/student/books/': typeof StudentBooksIndexRoute
  '/admin/books/$bookId/chapters': typeof AdminBooksBookIdChaptersRoute
  '/student/books/$bookId/chapters': typeof StudentBooksBookIdChaptersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz-setup': typeof QuizSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/books': typeof AdminBooksRouteWithChildren
  '/admin/coming-soon': typeof AdminComingSoonRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mcq-upload': typeof AdminMcqUploadRoute
  '/admin/payment-proofs': typeof AdminPaymentProofsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/bookmarks': typeof StudentBookmarksRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quiz-review': typeof StudentQuizReviewRoute
  '/student/quiz-session': typeof StudentQuizSessionRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/quiz/$chapterId': typeof StudentQuizChapterIdRoute
  '/student/books': typeof StudentBooksIndexRoute
  '/admin/books/$bookId/chapters': typeof AdminBooksBookIdChaptersRoute
  '/student/books/$bookId/chapters': typeof StudentBooksBookIdChaptersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz-setup': typeof QuizSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/books': typeof AdminBooksRouteWithChildren
  '/admin/coming-soon': typeof AdminComingSoonRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mcq-upload': typeof AdminMcqUploadRoute
  '/admin/payment-proofs': typeof AdminPaymentProofsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/announcements': typeof StudentAnnouncementsRoute
  '/student/bookmarks': typeof StudentBookmarksRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/quiz-review': typeof StudentQuizReviewRoute
  '/student/quiz-session': typeof StudentQuizSessionRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/quiz/$chapterId': typeof StudentQuizChapterIdRoute
  '/student/books/': typeof StudentBooksIndexRoute
  '/admin/books/$bookId/chapters': typeof AdminBooksBookIdChaptersRoute
  '/student/books/$bookId/chapters': typeof StudentBooksBookIdChaptersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/quiz-setup'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/announcements'
    | '/admin/books'
    | '/admin/coming-soon'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/mcq-upload'
    | '/admin/payment-proofs'
    | '/admin/users'
    | '/student/analytics'
    | '/student/announcements'
    | '/student/bookmarks'
    | '/student/dashboard'
    | '/student/practice'
    | '/student/profile'
    | '/student/quiz-review'
    | '/student/quiz-session'
    | '/student/subscription'
    | '/admin/'
    | '/student/'
    | '/student/quiz/$chapterId'
    | '/student/books/'
    | '/admin/books/$bookId/chapters'
    | '/student/books/$bookId/chapters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/quiz-setup'
    | '/register'
    | '/reset-password'
    | '/admin/announcements'
    | '/admin/books'
    | '/admin/coming-soon'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/mcq-upload'
    | '/admin/payment-proofs'
    | '/admin/users'
    | '/student/analytics'
    | '/student/announcements'
    | '/student/bookmarks'
    | '/student/dashboard'
    | '/student/practice'
    | '/student/profile'
    | '/student/quiz-review'
    | '/student/quiz-session'
    | '/student/subscription'
    | '/admin'
    | '/student'
    | '/student/quiz/$chapterId'
    | '/student/books'
    | '/admin/books/$bookId/chapters'
    | '/student/books/$bookId/chapters'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/quiz-setup'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/admin/announcements'
    | '/admin/books'
    | '/admin/coming-soon'
    | '/admin/complaints'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/mcq-upload'
    | '/admin/payment-proofs'
    | '/admin/users'
    | '/student/analytics'
    | '/student/announcements'
    | '/student/bookmarks'
    | '/student/dashboard'
    | '/student/practice'
    | '/student/profile'
    | '/student/quiz-review'
    | '/student/quiz-session'
    | '/student/subscription'
    | '/admin/'
    | '/student/'
    | '/student/quiz/$chapterId'
    | '/student/books/'
    | '/admin/books/$bookId/chapters'
    | '/student/books/$bookId/chapters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  QuizSetupRoute: typeof QuizSetupRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-setup': {
      id: '/quiz-setup'
      path: '/quiz-setup'
      fullPath: '/quiz-setup'
      preLoaderRoute: typeof QuizSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coming-soon': {
      id: '/admin/coming-soon'
      path: '/coming-soon'
      fullPath: '/admin/coming-soon'
      preLoaderRoute: typeof AdminComingSoonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mcq-upload': {
      id: '/admin/mcq-upload'
      path: '/mcq-upload'
      fullPath: '/admin/mcq-upload'
      preLoaderRoute: typeof AdminMcqUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-proofs': {
      id: '/admin/payment-proofs'
      path: '/payment-proofs'
      fullPath: '/admin/payment-proofs'
      preLoaderRoute: typeof AdminPaymentProofsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/analytics': {
      id: '/student/analytics'
      path: '/analytics'
      fullPath: '/student/analytics'
      preLoaderRoute: typeof StudentAnalyticsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/announcements': {
      id: '/student/announcements'
      path: '/announcements'
      fullPath: '/student/announcements'
      preLoaderRoute: typeof StudentAnnouncementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/bookmarks': {
      id: '/student/bookmarks'
      path: '/bookmarks'
      fullPath: '/student/bookmarks'
      preLoaderRoute: typeof StudentBookmarksRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz-review': {
      id: '/student/quiz-review'
      path: '/quiz-review'
      fullPath: '/student/quiz-review'
      preLoaderRoute: typeof StudentQuizReviewRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz-session': {
      id: '/student/quiz-session'
      path: '/quiz-session'
      fullPath: '/student/quiz-session'
      preLoaderRoute: typeof StudentQuizSessionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/subscription': {
      id: '/student/subscription'
      path: '/subscription'
      fullPath: '/student/subscription'
      preLoaderRoute: typeof StudentSubscriptionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/books/': {
      id: '/student/books/'
      path: '/books'
      fullPath: '/student/books/'
      preLoaderRoute: typeof StudentBooksIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz/$chapterId': {
      id: '/student/quiz/$chapterId'
      path: '/quiz/$chapterId'
      fullPath: '/student/quiz/$chapterId'
      preLoaderRoute: typeof StudentQuizChapterIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/books/$bookId/chapters': {
      id: '/admin/books/$bookId/chapters'
      path: '/$bookId/chapters'
      fullPath: '/admin/books/$bookId/chapters'
      preLoaderRoute: typeof AdminBooksBookIdChaptersRouteImport
      parentRoute: typeof AdminBooksRoute
    }
    '/student/books/$bookId/chapters': {
      id: '/student/books/$bookId/chapters'
      path: '/books/$bookId/chapters'
      fullPath: '/student/books/$bookId/chapters'
      preLoaderRoute: typeof StudentBooksBookIdChaptersRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminBooksRouteChildren {
  AdminBooksBookIdChaptersRoute: typeof AdminBooksBookIdChaptersRoute
}

const AdminBooksRouteChildren: AdminBooksRouteChildren = {
  AdminBooksBookIdChaptersRoute: AdminBooksBookIdChaptersRoute,
}

const AdminBooksRouteWithChildren = AdminBooksRoute._addFileChildren(
  AdminBooksRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBooksRoute: typeof AdminBooksRouteWithChildren
  AdminComingSoonRoute: typeof AdminComingSoonRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMcqUploadRoute: typeof AdminMcqUploadRoute
  AdminPaymentProofsRoute: typeof AdminPaymentProofsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBooksRoute: AdminBooksRouteWithChildren,
  AdminComingSoonRoute: AdminComingSoonRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMcqUploadRoute: AdminMcqUploadRoute,
  AdminPaymentProofsRoute: AdminPaymentProofsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAnalyticsRoute: typeof StudentAnalyticsRoute
  StudentAnnouncementsRoute: typeof StudentAnnouncementsRoute
  StudentBookmarksRoute: typeof StudentBookmarksRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentPracticeRoute: typeof StudentPracticeRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentQuizReviewRoute: typeof StudentQuizReviewRoute
  StudentQuizSessionRoute: typeof StudentQuizSessionRoute
  StudentSubscriptionRoute: typeof StudentSubscriptionRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentQuizChapterIdRoute: typeof StudentQuizChapterIdRoute
  StudentBooksIndexRoute: typeof StudentBooksIndexRoute
  StudentBooksBookIdChaptersRoute: typeof StudentBooksBookIdChaptersRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAnalyticsRoute: StudentAnalyticsRoute,
  StudentAnnouncementsRoute: StudentAnnouncementsRoute,
  StudentBookmarksRoute: StudentBookmarksRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentPracticeRoute: StudentPracticeRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentQuizReviewRoute: StudentQuizReviewRoute,
  StudentQuizSessionRoute: StudentQuizSessionRoute,
  StudentSubscriptionRoute: StudentSubscriptionRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentQuizChapterIdRoute: StudentQuizChapterIdRoute,
  StudentBooksIndexRoute: StudentBooksIndexRoute,
  StudentBooksBookIdChaptersRoute: StudentBooksBookIdChaptersRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  QuizSetupRoute: QuizSetupRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
